server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/uberforhaircut?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123

mybatis:
  mapper-locations: classpath:mapper/*.xml
