server:
  port: 19200

spring:
  application:
    name: gateway-shop
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: service-shop-route
          uri: lb://service-shop
          predicates:
            - Path=/ios/shops/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 30
                redis-rate-limiter.burstCapacity: 100
  redis:
    port: 6379

management:
  endpoints:
    gateway:
      enable: true
    web:
      exposure:
        include: true
