server:
  port: 8001


spring:
  application:
    name: cloud-hystrix-payment-service

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
    fetch-registry: true
  instance:
    instance-id: payment-hystrix8001
    prefer-ip-address: true

