server:
  port: 9001

spring:
  application:
    name: gateway-user
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: service-user-route
          #uri: http://localhost:9011
          uri: lb://service-user
          predicates:
          #  - Host=localhost**
            - Path=/ios/users/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
  redis:
    port: 6379
management:
  endpoints:
    gateway:
      enable: true
    web:
      exposure:
        include: true
