server:
  port: 9001

spring:
  application:
    name: gateway-user
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE



management:
  endpoints:
    gateway:
      enable: true
    web:
      exposure:
        include: true
