server:
  port: 9001

spring:
  application:
    name: gateway-user
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: service-user-route
          uri: lb://service-user
          predicates:
          #  - Host=localhost**
            - Path=/ios/users/**
          filters:
            - StripPrefix=1


management:
  endpoints:
    gateway:
      enable: true
    web:
      exposure:
        include: true
