server:
  port: 9011

spring:
  application:
    name: service-user
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/user?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 'root'
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bristol.project.entity


