server:
  port: 8001


spring:
  application:
    name: cloud-payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/payment?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 'root'
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
    fetch-registry: true
  instance:
    instance-id: payment8001
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bristol.project.entities

