server:
  port: 18080

spring:
  application:
    name: gateway-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: service-booking-route
          uri: lb://service-booking
          predicates:
            - Path=/ios/bookings/**
          filters:
            - StripPrefix=1
        - id: service-shop-route
          uri: lb://service-shop
          predicates:
            - Path=/ios/shops/**
          filters:
            - StripPrefix=1
        - id: service-uaa-route
          uri: lb://service-uaa
          predicates:
            - Path=/ios/uaa/**
          filters:
            - StripPrefix=1
        - id: service-user-route
          uri: lb://service-user
          predicates:
            - Path=/ios/users/**
          filters:
            - StripPrefix=1
swagger:
  services: /ios/bookings,/ios/shops,/ios/uaa,/ios/users

management:
  endpoints:
    gateway:
      enable: true
    web:
      exposure:
        include: true
